### ISSUE TITLE
downloading error

### ISSUE THREAD

**Issue by shadowninja024** [m4mallu/tube#4]
Hi thanks for the repo 
i'm facing this error when i try to download after selecting certain formate in tg bot

Error :

Some error occurred while the process !
 Plz try again later..

can you please help me where i went wrong?

**Comment by m4mallu** [comment]
send me any URL which throws this error...

**Comment by GreyMatter658** [comment]
Yes same thing happened with me neither URL downloading works nor inline mode.

**Comment by m4mallu** [comment]
Check the bot is in Inline mode or not. !

**Comment by GreyMatter658** [comment]
Bro i also checked bot inline mode it didn't work either.

**Comment by GreyMatter658** [comment]
![Uploading Screenshot_20220128_090354.jpg…]()

**Comment by m4mallu** [comment]
Not able to open this image! upload it in telegra.ph and share the link
